# Generated by Django 4.1.7 on 2023-04-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_accessrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='topic_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='playtype',
            field=models.CharField(max_length=30),
        ),
    ]
